### ISSUE TITLE
use case: testing helpers

### ISSUE THREAD

**Issue by tmzane** [xakep666/unusual_generics#1]
hi!

first, thank you for the repo, I've found it quite interesting to play with 👍

I'd like to suggest another use case, it's not that _unusual_, but it might be worth your attention. so it's basically testing helpers, similar to [stretchr/testify](https://github.com/stretchr/testify) and [matryer/is](https://github.com/matryer/is). the idea is to use generics to specify which testing method to call, `t.Errorf` or `t.Fatalf`. I've published the implementation as a [gist](https://gist.github.com/junk1tm/2eb9b45a7b816b6304177a487e47204d), could you take a look?

here's a small usage example:
```go
noerr[F](t, err)            // t.Fatalf if err != nil
equal[E](t, cfg.Port, 8080) // t.Errorf if cfg.Port != 8080
```

what do you think? thanks again

**Comment by xakep666** [comment]
Looks good to remove duplication between `assert` and `require` but usage of `any(t).(type)` looks a bit clumsy. I suggest empty struct based type approach like https://github.com/xakep666/unusual_generics/blob/master/time_format.go#L14

**Comment by tmzane** [comment]
speaking of `any(t).(type)`, `T E | F` kind of imitates sum type and unfortunately won't compile without casting to `any` in type switch. I'm looking forward to native sum types support in future version of Go

could you provide an example of how to implement something similar using empty struct based type approach?

**Comment by xakep666** [comment]
something like
```go
type ErrorReporter interface {
	~struct{}
	reporter() func(t *testing.T, msg string, args ...any)
}

type F struct{}

func (F) reporter() func(t *testing.T, msg string, args ...any) { return (*testing.T).Fatalf }

type E struct{}

func (E) reporter() func(t *testing.T, msg string, args ...any) { return (*testing.T).Errorf }

func report[T ErrorReporter](t *testing.T, msg string, args ...any) {
	(*new(T)).reporter()(t, msg, args...)
}

func noerr[T ErrorReporter](t *testing.T, err error) {
	t.Helper()
	if err != nil {
		report[T](t, "got %v; want no error", err)
	}
}
```

**Comment by tmzane** [comment]
interesting, I'll take a look

**Comment by tmzane** [comment]
hey @xakep666, just to let you know, I've combined the initial idea and your suggestion into a library https://github.com/junk1tm/assert

thanks again for the inspiration ❤️
